### ISSUE TITLE
No 3D molecule generate

### ISSUE THREAD

**Issue by groponp** [durrantlab/gypsum_dl#2] opened 2023-08-25 23:36 UTC
Dear developers, 
I'm try convert it C/C(=C\CC[C@@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO mol, but always experiment error generating 3D estructure. 

please help me.

**Comment by groponp** [comment] 2023-08-25 23:39
I'm sorry the smiles is : CC(=CCCC1(C2CC3C1(C3C2)C)C)CO

**Comment by jacobdurrant** [comment] 2023-09-01 19:36
Thanks for reaching out! It's good to hear from you again. Could you please provide me with the exact error message? It would help me better understand the specific issue you're facing.

From a quick look at the structure you shared, I suspect the challenge in generating the 3D geometry might be due to the complex tricycloheptane substructure. It may be difficult for RDKit, the library that Gypsum uses, to assign atomic coordinates in such a case.

If you could give me more details about the error, I'd be happy to help you further.

**Comment by groponp** [comment] 2023-09-03 01:53
I haven't exact error now, but the error is 3D can't be generate and it is save to a file with name  gypsum_failed.smi , but any of theses can be fix if i run again , but these not  generate 3D structure.

**Comment by jacobdurrant** [comment] 2023-09-15 21:39
Unfortunately, I wasn't able to reproduce your error:

```bash
(! 561)-> python run_gypsum_dl.py --source ./test.smi

If you use Gypsum-DL in your research, please cite:

Ropp, Patrick J., Jacob O. Spiegel, Jennifer L. Walker, Harrison Green,
Guillermo A. Morales, Katherine A. Milliken, John J. Ringe, and Jacob D. Durrant.
(2019) Gypsum-DL: An Open-source Program for Preparing Small-molecule Libraries for 
Structure-based Virtual Screening. Journal of Cheminformatics 11:1. 
doi:10.1186/s13321-019-0358-3.

WARNING: Running Gypsum-DL without the Durrant-lab filters. In looking over many
    Gypsum-DL-generated variants, we have identified a number of substructures
    that, though technically possible, strike us as improbable or otherwise
    poorly suited for virtual screening. We strongly recommend removing these by
    running Gypsum-DL with the --use_durrant_lab_filters option.

Loading molecules from test.smi...
    Untitled ligand on line 1. Naming that ligand untitled_line_1. All
        associated files will be referred to with this name.
Desalting all molecules (i.e., keeping only largest fragment).
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: CC(=CCCC1(C)C2CC3C(C2)C31C)CO
Ionizing all molecules...
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: CC(=CCCC1(C)C2CC3C(C2)C31C)CO
Generating tautomers for all molecules...
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: CC(=CCCC1(C)C2CC3C(C2)C31C)CO
Not applying Durrant-lab filters
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: CC(=CCCC1(C)C2CC3C(C2)C31C)CO
Enumerating all possible enantiomers for all molecules...
    CC(=CCCC1(C)C2CC3C(C2)C31C)CO (untitled_line_1) has 8 enantiomers when
        chiral centers with no specified chirality are systematically varied.
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: CC(=CCC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #1: CC(=CCC[C@]1(C)C2C[C@H]3[C@H](C2)C31C)CO
Enumerating all possible cis-trans isomers for all molecules...
    CC(=CCC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO has 1 double bond(s) with
        unspecified stereochemistry.
    CC(=CCC[C@]1(C)C2C[C@H]3[C@H](C2)C31C)CO has 1 double bond(s) with
        unspecified stereochemistry.
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: C/C(=C\CC[C@]1(C)C2C[C@H]3[C@H](C2)C31C)CO
            Mol #1: C/C(=C/CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #2: C/C(=C/CC[C@]1(C)C2C[C@H]3[C@H](C2)C31C)CO
            Mol #3: C/C(=C\CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
Converting all molecules to 3D structures.
    WARNING: Could not generate 3D geometry for [H]OC([H])([H])/C(=C(\[H])C([H])
        ([H])C([H])([H])[C@]1(C([H])([H])[H])C2([H])C([H])([H])[C@]3([H])C1(C([H
        ])([H])[H])[C@@]3([H])C2([H])[H])C([H])([H])[H] (untitled_line_1).
        Molecule discarded.
    WARNING: Could not generate 3D geometry for [H]OC([H])([H])/C(=C(/[H])C([H])
        ([H])C([H])([H])[C@]1(C([H])([H])[H])C2([H])C([H])([H])[C@]3([H])C1(C([H
        ])([H])[H])[C@@]3([H])C2([H])[H])C([H])([H])[H] (untitled_line_1).
        Molecule discarded.
Generating several conformers of molecules with non-aromatic rings (boat vs.
    chair, etc.)...
Minimizing all 3D molecular structures...
    Contents of MolContainers
        MolContainer #0 (untitled_line_1)
            Mol #0: C/C(=C/CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #1: C/C(=C\CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #2: C/C(=C\CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #3: C/C(=C/CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
            Mol #4: C/C(=C\CC[C@]1(C)C2C[C@H]3[C@@H](C2)C31C)CO
Saving molecules associated with...
    CC(=CCCC1(C2CC3C1(C3C2)C)C)CO

Start time at: 2023-09-15 17:37:02.727942
End time at:   2023-09-15 17:37:46.946637
Total time at: 0:00:44.218695
Finished Gypsum-DL
```

Perhaps if you send the exact error I'll be able to debug better. I'll go ahead and close this issue for now, but feel free to reopen it when you have more information. Take care.

**Closed as completed by jacobdurrant** 2023-09-15 21:39 UTC
